repos:
- repo: local
  hooks:
  - id: run-tests
    name: Run Tests
    entry: ./tests/runtests
    language: script
    pass_filenames: false
    files: ''
    always_run: true
    stages:
    - commit
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 23.9.1  # Use the specific version of Black you want to run
  hooks:
  - id: black
    language: python
