---
#  Based on the argo-cd setup
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [uplaybook]
        options:
          show_source: false
extra_css:
- assets/versions.css
extra_javascript:
- assets/versions.js
markdown_extensions:
- toc:
    permalink: true
    toc_depth: 3
- markdown_include.include
- codehilite:
    css_class: highlight
- admonition
- pymdownx.superfences
repo_url: https://github.com/linsomniac/uplaybook
site_name: uPlaybook - Declarative System/Project Setup
strict: true
theme:
  favicon: assets/favicon.png
  font:
    text: Work Sans
  logo: assets/logo.png
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: teal
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: teal
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
nav:
- Overview: index.md
- Getting Started: getting_started.md
- Installing: installing.md
- uPlaybook Library: uplaybook_library.md
- Playbooks:
  - What is a Playbook: playbooks/what_is.md
  - Basics: playbooks/basics.md
- Templating: templating.md
- Hacking: hacking.md
- Task Reference:
  - Core Tasks: tasks/core.md
  - File System Tasks: tasks/fs.md
  - uPlaybook Internals: tasks/internals.md
- For Ansible Users: for_ansible_users.md
- Releases ⧉: https://github.com/linsomniac/uplaybook/releases
