---
#  Based on the argo-cd setup
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [uplaybook]
        options:
          show_source: false
watch:
  - uplaybook
extra_css:
- assets/versions.css
extra_javascript:
- assets/versions.js
markdown_extensions:
- toc:
    permalink: true
    toc_depth: 3
- markdown_include.include
- codehilite:
    css_class: highlight
- admonition
- pymdownx.superfences
repo_url: https://github.com/linsomniac/uplaybook
site_name: uPlaybook - Declarative System/Project Setup
strict: true
theme:
  favicon: assets/favicon.png
  font:
    text: Work Sans
  logo: assets/logo.png
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: teal
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: teal
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
nav:
- Overview: index.md
- Getting Started: getting_started.md
- Installing: installing.md
- Running: running.md
- uPlaybook Library: uplaybook_library.md
- Playbooks:
  - What is a Playbook: playbooks/what_is.md
  - Basics: playbooks/basics.md
- Templating: templating.md
- Including Sub-Playbooks: include.md
- Hacking: hacking.md
- Task Reference:
  - Core Tasks: tasks/core.md
  - File System Tasks: tasks/fs.md
  - pyinfra:
    - Introduction: tasks/pyinfra/intro.md
    - apk: tasks/pyinfra/apk.md
    - apt: tasks/pyinfra/apt.md
    - brew: tasks/pyinfra/brew.md
    - bsdinit: tasks/pyinfra/bsdinit.md
    - choco: tasks/pyinfra/choco.md
    - dnf: tasks/pyinfra/dnf.md
    - files: tasks/pyinfra/files.md
    - gem: tasks/pyinfra/gem.md
    - git: tasks/pyinfra/git.md
    - iptables: tasks/pyinfra/iptables.md
    - launchd: tasks/pyinfra/launchd.md
    - lxd: tasks/pyinfra/lxd.md
    - mysql: tasks/pyinfra/mysql.md
    - npm: tasks/pyinfra/npm.md
    - openrc: tasks/pyinfra/openrc.md
    - pacman: tasks/pyinfra/pacman.md
    - pip: tasks/pyinfra/pip.md
    - pkg: tasks/pyinfra/pkg.md
    - pkgin: tasks/pyinfra/pkgin.md
    - postgresql: tasks/pyinfra/postgresql.md
    - puppet: tasks/pyinfra/puppet.md
    - server: tasks/pyinfra/server.md
    - ssh: tasks/pyinfra/ssh.md
    - systemd: tasks/pyinfra/systemd.md
    - sysvinit: tasks/pyinfra/sysvinit.md
    - upstart: tasks/pyinfra/upstart.md
    - vzctl: tasks/pyinfra/vzctl.md
    - windows: tasks/pyinfra/windows.md
    - windows_files: tasks/pyinfra/windows_files.md
    - xbps: tasks/pyinfra/xbps.md
    - yum: tasks/pyinfra/yum.md
    - zypper: tasks/pyinfra/zypper.md
  - uPlaybook Internals: tasks/internals.md
- For Ansible Users: for_ansible_users.md
- Releases ⧉: https://github.com/linsomniac/uplaybook/releases
