#!/bin/bash -eu
#
#  Tests for uPlaybook

if [ -d .git ]; then
  PYTHONPATH=$(pwd)
  TESTDIR=$(pwd)/tests
else
  PYTHONPATH=$(pwd)/..
  TESTDIR=$(pwd)
fi
UP2='python3 -c "from uplaybook.cli import cli; cli()" --up-full-traceback'
export UP2
export PYTHONPATH
export TESTDIR

cd "$TESTDIR"
for TEST in test_*; do
  cd "$TESTDIR"
  [ ! -f "$TEST"/run_test ] && continue
  cd "$TESTDIR"/"$TEST"
  echo "*** $TEST ***"
  if ! ./run_test; then
    echo "!!! TEST FAILED"
    exit 1
  fi
done

echo "TEST PASSED"
#  No python tests yet
#cd "$TESTDIR"
#python3 -m pytest
#exit "$?"
