#!/usr/bin/env python3

"""
Create a new uplaybook.

This playbook creates a new, example, uplaybook.  This can be
used as a skeleton to create new uplaybooks.
"""

from uplaybook import fs, core

core.playbook_args(
        core.Argument(name="playbook_name",
                      description="Name of playbook to create, creates directory of this name."),
        core.Argument(name="force", default=False, type="bool",
                      description="Reset the playbook back to the default if it already exists (default is to abort if playbook already exists)."),
        )

if fs.exists(ARGS.playbook_name) and not ARGS.force:
    core.fail(msg=f"*** ERROR: Playbook {ARGS.playbook_name} already exists.  Will not overwrite without '--force'")

fs.mkdir(dst=ARGS.playbook_name)
with fs.cd(dst=ARGS.playbook_name):
    fs.cp(src="playbook.j2", dst="playbook")
