#!/bin/bash -eu
#
#  Test the basics

RETCODE=0

eval "$UP2 basics.pb" || RETCODE=$?
eval "$UP2 notify.pb" || RETCODE=$?
eval "$UP2 include.pb" || RETCODE=$?
eval "$UP2 args.pb" release --arg1 --arg2=value || RETCODE=$?

[ "${UP_TEST_CLEANUP:-yes}" = "yes" ] && rm -rf testdir
exit $RETCODE
