name: Build and Deploy Docs

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    #permissions:
    #  contents: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12  # or another version you prefer

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx m2r2
        pip install .
        # If you use any sphinx extensions or themes, install them here as well

    - name: Build Docs
      run: |
        pip install --requirement docs/requirements.txt
        PYTHONPATH=. mkdocs build

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: 'site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

#    - name: Deploy to GitHub Pages
#      uses: peaceiris/actions-gh-pages@v3
#      if: github.ref == 'refs/heads/main'
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: ./docs/build
